### ISSUE TITLE
Testcase:  SWU_E2.2.5: Content pages, Header

### ISSUE THREAD

**Issue by crochefort** [wet-boew/wet-boew-wpss#66]
Version 4.8.0 

Testcase:  SWU_E2.2.5: Content pages, Header
    Line:  63 Column:  20
    Invalid 'href' 'http://canada.ca/en/gov/dept/index.html' in GC navigation bar link # 3 expecting 'http://www.canada.ca/en/gov/dept/index.html'
    Source line: <li id="gcwu-gcnb3"><a rel="external" href="http://canada.ca/en/gov/dept/index.html">Departments</a></li>

Can you change your script to allow the http://canada.ca ...

as per TBS : http://tbs-sct.gc.ca/ws-nw/mo-om/ts-st/p7-eng.asp#Section11_1_1

Behaviour:

Canada.ca links to http://canada.ca/en/index.html or http://canada.ca/fr/index.html
Services links to http://www.servicecanada.gc.ca/eng/home.shtml or http://www.servicecanada.gc.ca/fra/accueil.shtml
Departments ("Ministères") links to http://canada.ca/en/gov/dept/index.html or http://canada.ca/fr/gouv/min/index.html
Language selection links take the user to the equivalent content in that language.
The official language selection link takes the user to the same Web page in the other official language.

The Departments list don't show the www.

Thank you

**Comment by irwink** [comment]
The latest WET 4.0.10 Web Usability theme example pages contain the www.canada.ca domain for the GC navigation links (not matching the written spec).  The example pages also are missing the file name portion of the Travel and Health links in the GC Footer.  So rather than checking the href values, the check will be limited to the link text only.

Quick fix is to replace the file conf\so_clf_check.config (https://github.com/wet-boew/wet-boew-wpss/blob/master/CLF_Check/so_clf_check.config)

**Comment by irwink** [comment]
HREF value checking suppressed for footer links in version 5.0.0.  The anchor value is still checked.
