### ISSUE TITLE
StackOverflowError while evaluating HTML schema. The checker requires a java thread stack size of at least 512k. 

### ISSUE THREAD

**Issue by wet-boew-testing** [wet-boew/wet-boew-wpss#86]
The WPSS tool appears to generate an Overflow Error.  Is there a way to prevent this error?

Here is the results when evaluating  https://www.gcsurplus.ca/mn-eng.cfm?snc=ouv-log&ouvlog=1

1:  https://www.gcsurplus.ca/mn-eng.cfm?snc=ouv-log&ouvlog=1
  Testcase:  HTML_VALIDATION
    Runtime Error "java -Xss512k -jar ".\lib\vnu.jar" --errors-only --format json "C:\Users\langlog1\AppData\Local\Temp\WPSS_TOOL_gmnotwSkQ6.html""
 "StackOverflowError while evaluating HTML schema.
The checker requires a java thread stack size of at least 512k.
Consider invoking java with the -Xss option. For example:

  java -Xss512k -jar ~/vnu.jar FILE.html
"

**Comment by irwink** [comment]
The problem is with 32 bit versus 64 bit Java.  The stack size is set to 512k, which is adequate for a 32 bit system, while a 1024k stack is needed for a 64 bit system.  A quick fix is to exit the lib/html_validate.pm module and change the Windows Java options at the bottom of the file to -Xss1024k.

**Comment by irwink** [comment]
Stack size of 32 and 64 bit windows set as required in version 6.3.0
